name: cicd

on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - master
  schedule:
    - cron: "0 7 * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        env:
          DEGAUSS_SCHEMA_REGISTRY_URL: ${{ secrets.DEGAUSS_SCHEMA_REGISTRY_URL }}
          DEGAUSS_SCHEMA_REGISTRY_USER: ${{ secrets.DEGAUSS_SCHEMA_REGISTRY_USER }}
          DEGAUSS_SCHEMA_REGISTRY_PASS: ${{ secrets.DEGAUSS_SCHEMA_REGISTRY_PASS }}
        with:
          command: test

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true

      - name: Run clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -- -D warnings

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install tarpaulin
        if: github.ref == 'refs/heads/master' || github.event_name == 'pull_request'
        continue-on-error: true
        run: |
          cargo install cargo-tarpaulin

      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
            ~/.cargo/bin
          key: ${{ runner.os }}-cargo-bin-${{ hashFiles('**/Cargo.lock') }}

      - name: Generate coverage report
        if: github.ref == 'refs/heads/master' || github.event_name == 'pull_request'
        continue-on-error: true
        run: |
          cargo tarpaulin --out Xml --all --all-features

      - name: Upload to Codecov
        if: github.ref == 'refs/heads/master' || github.event_name == 'pull_request'
        continue-on-error: true
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: cobertura.xml
